# clusters/my-cluster/helm-releases/postgresql.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-db
  namespace: postgres
spec:
  releaseName: my-postgres
  chart:
    spec:
      chart: postgresql
      version: 11.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  values:
    global:
      postgresql:
        auth:
          existingSecret: postgres-secret  # Use existing Kubernetes Secret
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "standard"
    service:
      type: LoadBalancer
